### ISSUE TITLE
how does the visitor pattern works?

### ISSUE THREAD

**Issue by tricktresor** [keremkoseoglu/addict#7]
Hey Kerem, 
when time allows, would you like to explain how the visitor pattern works in this case (ycl_addict_class->accept( visitor ) )?

I know there is the design pattern _visitor_ explained on Wikipedia and other web sites, but I do not understand this pattern. 

I really would appreciate some coaching in this topic! ;)

Thanks
~Enno

**Comment by keremkoseoglu** [comment]
Visitor is used to extend class functionality without editing its code. 

Normally, you could add new methods to YCL_ADDICT_CLASS. But that would bloat the class and maybe you shouldn't be editing the class at all (external namespace, etc).

In such cases, you add an ACCEPT method to the master class, which expects an interface. Each visitor class (implementing this interface) is evaluated as a method.

Bonus: I happen to have a published book on the subject: [Design Patterns in ABAP Objects](https://www.sap-press.com/design-patterns-in-abap-objects_4277/)

Since this is not an "Addict" issue, I'm closing this.
